### ISSUE TITLE
demo broken

### ISSUE THREAD

**Issue by mcollina** [vidi-insights/vidi-dashboard#126]
I've just pulled master 

```js
ReferenceError: data is not defined
    at Seneca.<anonymous> (/Users/matteo/Repositories/vidi-dashboard/node_modules/vidi-toolbag-influx/toolbag-influx.js:124:27)
    at Seneca.delegate.prior (/Users/matteo/Repositories/vidi-dashboard/node_modules/seneca/seneca.js:1447:21)
    at Seneca.event_loop_stats (/Users/matteo/Repositories/vidi-dashboard/node_modules/vidi-toolbag-influx/toolbag-influx.js:122:10)
    at /Users/matteo/Repositories/vidi-dashboard/node_modules/seneca/seneca.js:1134:22
    at act_param_check (/Users/matteo/Repositories/vidi-dashboard/node_modules/seneca/seneca.js:1478:17)
    at Object.execute_action [as fn] (/Users/matteo/Repositories/vidi-dashboard/node_modules/seneca/seneca.js:1078:7)
    at Immediate._onImmediate (/Users/matteo/Repositories/vidi-dashboard/node_modules/seneca/node_modules/gate-executor/gate-executor.js:135:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by mcdonnelldean** [comment]
Hmm? Let me see, it should work, I'll fix and branch for you into 'demo'

**Comment by mcdonnelldean** [comment]
I've pulled and confirmed it runs, can you

1. `rm -rf /node_modules /dist'
2. `npm run build; npm run start`

I've create a stable branch for people looking to play with it. This will keep the app free from regression crashing. https://github.com/vidi-insights/vidi-dashboard/tree/stable-demo

**Comment by mcollina** [comment]
Done, still not working.

**Comment by mcdonnelldean** [comment]
@mcollina 

Is Influx running? This is a raw error dump (I need to put it behind a switch), basically queries to influx are  not returning any data.

**Comment by mcollina** [comment]
Influx was not running, that solved it! A variable not being defined is not a good error :(.

**Comment by mcdonnelldean** [comment]
Agreed! Fixing now :D

**Comment by mcdonnelldean** [comment]
@mcollina `stable-demo` is now updated, please do an install and build again as I have changed some of the modules. It should spit out a connection refused error only once now and then sit idle.
